"""add telegram id

Revision ID: 8a3a7a14b1c9
Revises: 7445e9c167f7
Create Date: 2024-07-29 21:37:17.948148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a3a7a14b1c9"
down_revision: Union[str, None] = "7445e9c167f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("hashed_password", sa.LargeBinary(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("telegram_id", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(None, "user", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "telegram_id")
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
