"""delete password field

Revision ID: 3a04e3fd38ea
Revises: eceaa0b7500c
Create Date: 2024-07-29 05:20:11.767915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a04e3fd38ea"
down_revision: Union[str, None] = "eceaa0b7500c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
