"""add nullable email

Revision ID: 7445e9c167f7
Revises: 3a04e3fd38ea
Create Date: 2024-07-29 05:22:02.270749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7445e9c167f7"
down_revision: Union[str, None] = "3a04e3fd38ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    # ### end Alembic commands ###
